# default
spring:
  profiles:
    active: local
  jpa:
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
decorator:
  datasource:
    p6spy:
      multiline: true
      enable-logging: true

springdoc:
  swagger-ui:
    path: /swagger-ui
    doc-expansion: list
    default-model-expand-depth: 2
    operations-sorter: alpha
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /rproject/**

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/rproject
    driver: org.postgresql.Driver
    username: rsupport
    password: rsupport
  upload:
    path: C:\dev\upload

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    driver: org.postgresql.Driver
    username: rsupport
    password: rsupport
  jpa:
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
  upload:
    path: C:\dev\test\upload
