spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/notice
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root
  jpa:
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
  upload:
    path: C:\dev\upload
decorator:
  datasource:
    p6spy:
      multiline: true
      enable-logging: true

springdoc:
  swagger-ui:
    path: /swagger-ui
#    enabled: true
    doc-expansion: list
    default-model-expand-depth: 2
    operations-sorter: alpha
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /**